### ISSUE TITLE
自定义处理器名称revcpuname无效

### ISSUE THREAD

**Issue by Good0007** [hackintosh-club/TianBang-13900H-ES-ITX-OpenCore#4]
感谢大佬提供efi，原来用的z390i，直接把黑果系统盘拿过来，换上efi就进去了。目前有个小问题：
我看efi里已经有设置revcpu和revcpuname，但是我这边一直不生效。当前系统是14.3的

**Comment by Good0007** [comment]
> OC界面按空格键，之后选择resetnvram，重启后重新进入macos系统

解决了，需要在processType那填上3842 不然不生效

**Comment by WuLongMiTaoLaiYiDa** [comment]
> > OC界面按空格键，之后选择resetnvram，重启后重新进入macos系统
> 
> 解决了，需要在processType那填上3842 不然不生效

配置文件里默认已经填写了3841 支持cpu显示
所以你后期改掉了哇？

**Comment by Good0007** [comment]
> > > OC界面按空格键，之后选择resetnvram，重启后重新进入macos系统
> > 
> > 
> > 解决了，需要在processType那填上3842 不然不生效
> 
> 配置文件里默认已经填写了3841 支持cpu显示 所以你后期改掉了哇？

嗯 刚开始换机型测试，自动覆盖掉了..
